services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        volumes:
            - .:/var/www/html
        depends_on:
            - mysql
        networks:
            - laravel

    nginx:
        image: nginx:alpine
        container_name: laravel_nginx
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    mysql:
        image: mysql:8.0
        container_name: laravel_db
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel

    cron:
        build:
            context: ./cron
            dockerfile: Dockerfile
        container_name: laravel_cron
        volumes:
            - .:/var/www/html
        depends_on:
            - app
        networks:
            - laravel

networks:
    laravel:
        driver: bridge

volumes:
    db_data:
